const Router = require('express')
const router = new Router()

const userRouter = require('./userRouter')
const courseRouter = require('./courseRouter')
const studentRouter = require('./studentRouter')
const groupRouter = require('./groupRouter')
const examRouter = require('./examRouter')
const galleryRouter = require('./galleryRouter')
const groupExamRouter = require('./groupExamRouter')
const examResultRouter = require('./examResultRouter')
const lectureInstructorRouter = require('./lectureInstructorRouter')
const drivingInstructorRouter = require('./drivingInstructorRouter')
const lectureScheduleRouter = require('./lectureScheduleRouter')
const drivingScheduleRouter = require('./drivingScheduleRouter')

router.use('/user', userRouter)
router.use('/course', courseRouter)
router.use('/student', studentRouter)
router.use('/group', groupRouter)
router.use('/exam', examRouter)
router.use('/gallery', galleryRouter)
router.use('/groupExam', groupExamRouter)
router.use('/examResult', examResultRouter)
router.use('/lector', lectureInstructorRouter)
router.use('/instructor', drivingInstructorRouter)
router.use('/lectures', lectureScheduleRouter)
router.use('/drivings', drivingScheduleRouter)

module.exports=router